name: Clock In
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 00 * * 1-5'
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3
    - name: Install latest Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - uses: nanasess/setup-chromedriver@v1
      with:
        # chromedriver-version: "106.0.5249.61"
        chromedriver-version: latest
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.1
    - run: go run . clock-in
      env:
        TZ: Asia/Jakarta
        TALENTA_EMAIL: ${{ secrets.TALENTA_EMAIL }}
        TALENTA_PASSWORD: ${{ secrets.TALENTA_PASSWORD }}
        LATITUDE: ${{ secrets.LATITUDE }}
        LONGITUDE: ${{ secrets.LONGITUDE }}
